// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioBlog.Api.Infrastructure.Data;

#nullable disable

namespace PortfolioBlog.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925223915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PortfolioBlog.Api.Domain.AdminState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("SessionEpoch")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdminState", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdminState_Single", "`Id` = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SessionEpoch = 1
                        });
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .UseCollation("utf8mb4_0900_bin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_0900_bin");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .UseCollation("utf8mb4_0900_bin");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending(true, false);

                    b.ToTable("Attachments", t =>
                        {
                            t.HasCheckConstraint("CK_Attachments_ContentType", "`ContentType` IN ('image/png', 'image/jpeg', 'image/gif', 'image/webp')");

                            t.HasCheckConstraint("CK_Attachments_FileName_NotBlank", "CHAR_LENGTH(TRIM(`FileName`)) > 0");

                            t.HasCheckConstraint("CK_Attachments_Sha256", "REGEXP_LIKE(`Sha256`, '^[0-9a-f]{64}\\\\z', 'c')");

                            t.HasCheckConstraint("CK_Attachments_Size", "`SizeBytes` BETWEEN 1 AND 10485760");
                        });
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("SeriesOrder")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_0900_bin");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending(true, false);

                    b.HasIndex("SeriesId", "SeriesOrder", "CreatedAt", "Id");

                    b.ToTable("Posts", t =>
                        {
                            t.HasCheckConstraint("CK_Posts_Content_Size", "LENGTH(`ContentMarkdown`) <= 204800");

                            t.HasCheckConstraint("CK_Posts_SeriesOrder_Positive", "`SeriesOrder` IS NULL OR `SeriesOrder` > 0");

                            t.HasCheckConstraint("CK_Posts_Series_Pair", "(`SeriesId` IS NULL) = (`SeriesOrder` IS NULL)");

                            t.HasCheckConstraint("CK_Posts_Slug_Format", "REGEXP_LIKE(`Slug`, '^[a-z0-9]+(-[a-z0-9]+)*\\\\z', 'c')");

                            t.HasCheckConstraint("CK_Posts_Title_NotBlank", "CHAR_LENGTH(TRIM(`Title`)) > 0");
                        });
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.PostTag", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId", "PostId");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_0900_bin");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Series", null, t =>
                        {
                            t.HasCheckConstraint("CK_Series_Slug_Format", "REGEXP_LIKE(`Slug`, '^[a-z0-9]+(-[a-z0-9]+)*\\\\z', 'c')");

                            t.HasCheckConstraint("CK_Series_Title_NotBlank", "CHAR_LENGTH(TRIM(`Title`)) > 0");
                        });
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_0900_bin");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags", t =>
                        {
                            t.HasCheckConstraint("CK_Tags_Name_NoSlash", "LOCATE('/', `Name`) = 0");

                            t.HasCheckConstraint("CK_Tags_Name_NotBlank", "CHAR_LENGTH(TRIM(`Name`)) > 0");
                        });
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.Post", b =>
                {
                    b.HasOne("PortfolioBlog.Api.Domain.Series", "Series")
                        .WithMany("Posts")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.PostTag", b =>
                {
                    b.HasOne("PortfolioBlog.Api.Domain.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioBlog.Api.Domain.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.Post", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.Series", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("PortfolioBlog.Api.Domain.Tag", b =>
                {
                    b.Navigation("PostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
